[[redirects]]
  from = "/*"
  to = "/404/404.html"
  status = 404

[[redirects]]
  from = "/sobreapac#info"
  to = "/html/sobreapac.html#sobrenosotros_info"
  status = 200

[[redirects]]
  from = "/asociarse#info"
  to = "/html/asociarse.html#asociarse_info"
  status = 200

[[redirects]]
  from = "/voluntarios#info"
  to = "/html/voluntarios.html#voluntarios_requisitos"
  status = 200